### ISSUE TITLE
kintoneの絞り込みとページングに同期する

### ISSUE THREAD

**Issue by mura-** [mura-/kintone-spreadsheet-no-longer-maintained#2]
現在、スプレッドシートはkintoneの絞り込みとページングに対応しておらず、全部出力される。

絞り込みとページングに同期すれば使い勝手がよくなりそうなので、対応する。
懸念として、ソートをかけている時、新規レコード追加したときの挙動がわかりにくい、などがある。

**Comment by MccKee** [comment]
プラグインの提供ありがとうございます。
kintoneの絞り込みとページングの対応について今後リリースの見込みはございますでしょうか。
ご教示頂けると幸いです。宜しくお願いいたします。

**Comment by mura-** [comment]
それも含めて今は色々制約あるので、対応していきたいとおもいます。なるべくは今年中にやれることはやります。

**Comment by MccKee** [comment]
ご回答ありがとうございます！！
恩恵に預かり大変感謝しています。
今後のリリース、心待ちにさせていただきます。

**Comment by mura-** [comment]
@MccKee 

まだ正式版ではないですが、
ちょっと試してみたのでお先にお渡しします。何かあったらおしえてください。

[plugin.zip](https://github.com/mura-/kintone-spreadsheet/files/1346361/plugin.zip)

**Comment by mura-** [comment]
@MccKee 
上記変更を含んだものをリリースしました

https://github.com/mura-/kintone-spreadsheet/releases/tag/v0.9.5

**Comment by MccKee** [comment]
muraさんありがとうございます。
[先程気づきまして早速pluginしたところ添付のようなエラーとなりました。
![default](https://user-images.githubusercontent.com/29295701/31264776-392a9748-aaa6-11e7-8a1c-114a7352bcdc.png)
宜しくお願いいたします。

**Comment by mura-** [comment]
@MccKee https://github.com/mura-/kintone-spreadsheet/releases/tag/v0.9.5
こちらのものをつかった結果ですか？

**Comment by MccKee** [comment]
はい、そうです。

**Comment by mura-** [comment]
画面は使えない状態でしょうか?

**Comment by MccKee** [comment]
![default](https://user-images.githubusercontent.com/29295701/31267867-d1e81c36-aab4-11e7-9ac8-3c85783a6f75.png)

件数は表示されますが、一覧が出てこないような状況です。

**Comment by mura-** [comment]
こちらでも確認してみます。連絡ありがとうございます。

**Comment by MccKee** [comment]
すみません、宜しくお願いいたします。

**Comment by mura-** [comment]
@MccKee 試しにプラグインの設定しなおしてもらってもいいですか？原因をはっきりさせるために、表示を１つか２つくらいのフィールド数にしてほしいです

**Comment by MccKee** [comment]
muraさん、プラグインを入れなおしたら動きました。
すみませんでした。。。
このまま使用させていただきます！！

また何かあれば問合せさせていただくかと思いますが宜しくお願いいたします！

**Comment by mura-** [comment]
@MccKee よかったです。私の環境ではエラーにならなかったので。。
何かアレば連絡ください。

**Comment by MccKee** [comment]
いつもお世話になっています。
プラグインの関係なのかわからないのですが、以下のようなエラーが出ました。
何か心あたりがあれば教えていただけますでしょうか。

![default](https://user-images.githubusercontent.com/29295701/31752134-59768f98-b4c4-11e7-8ffe-f2a630e04407.png)
