### ISSUE TITLE
データは取り込んでいるが、画面が表示されない。

### ISSUE THREAD

**Issue by myanbear** [mura-/kintone-spreadsheet-no-longer-maintained#25]
基本的な所で躓いてしまっていますが、質問させて下さい。
2016年11月30日時点のkintoneにて、本プラグインを利用していますが、上手く表示が出来ません。
（kintone spreadsheet v0.9.2を利用）

１）kintoneシステム管理画面でのプラグイン取り込み→成功
２）アプリの設定画面でのプラグイン取り込み→成功
３）カスタマイズビューの設定→<div id="sheet"></div>のみ記述。
４）プラグインの設定→要素IDを入力して、表示したいフィールドを設定。
（アプリの更新も実施）

この後、カスタマイズビューを表示しても取得できているデータ件数は表示されますが、
実際のデータは何も表示されません。
（他のビューでデータ表示は可能です）

カスタマイズビューで、追加の記述などが必要でしょうか、
お手数ですが、ご教授頂ければ幸いです。

**Comment by mura-** [comment]
@myanbear 
大変返事が滞ってしまい申し訳ありません。
コンソールなどからエラーの内容を教えてもらえますでしょうか。時間が立ちすぎているので一旦ISSUEは閉じさせていただきます。
