### ISSUE TITLE
アプリコードの変更に対応する

### ISSUE THREAD

**Issue by mura-** [mura-/kintone-spreadsheet-no-longer-maintained#8]
アプリコードを変更するとレコード番号が変わって（数値だけではなくなる）しまうため `$id` を使うようにする

**Comment by north-river** [comment]
これって、getRecords部分の対応でしょうか？
設定時にレコード番号フィールドのフィールドコードを変えていてハマったとのフィードバックがありました。

**Comment by mura-** [comment]
はい、そこも含まれます。

**Comment by mura-** [comment]
@north-river 対応しました。
